<?php

namespace Database\Seeders;

use App\Models\Clinic;
use App\Models\Doctor;
use App\Models\DoctorService;
use App\Models\Membership;
use App\Models\Specialty;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Arr;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;

class DoctorExcelSeeder extends Seeder
{
    public function run(): void
    {
        $doctorRole = Role::firstOrCreate(['name' => 'doctor', 'guard_name' => 'web']);
        $rows = [
            ['first_name' => 'Cesar', 'last_name' => 'Yaghi', 'email' => 'cesar.yaghi@usj.edu.lb', 'phone' => '01613023, 03343864', 'birth_date' => '21/10/1964', 'gender' => 'Male', 'main_specialization' => 'Gastroenterology', 'sub_specializations' => 'Hepatology', 'country' => 'Lebanon', 'first_visit_price' => '100', 'followup_price' => '70', 'education' => 'MD,Msc', 'hospitals' => 'Hotel-Dieu de France', 'memberships' => '', 'services' => '', 'clinics' => '', 'languages' => 'English, French, Arabic'],
            ['first_name' => 'Fadi Hanna', 'last_name' => 'Sleilati', 'email' => 'fadi.sleilati@hdf.usj.edu.lb', 'phone' => '71764875', 'birth_date' => '1/1/1969', 'gender' => 'Male', 'main_specialization' => 'Aesthetic, reconstructive surgery', 'sub_specializations' => '', 'country' => 'Lebanon', 'first_visit_price' => '100', 'followup_price' => '70', 'education' => '', 'hospitals' => 'Hotel-Dieu de France', 'memberships' => '', 'services' => 'Plastic surgery', 'clinics' => 'Hotel-Dieu de France, Sin el fil', 'languages' => 'Arabic,French,English'],
            ['first_name' => 'Joseph', 'last_name' => 'Kattan', 'email' => 'jkattan62@hotmail.com', 'phone' => '03635913', 'birth_date' => '3/3/1962', 'gender' => 'Male', 'main_specialization' => 'Hematology, Oncology', 'sub_specializations' => 'Solid Tumors, Uro-Oncology', 'country' => 'Lebanon', 'first_visit_price' => '100', 'followup_price' => '70', 'education' => 'FM/USJ', 'hospitals' => 'Hotel-Dieu de France', 'memberships' => 'ASCO, ESMO, EHA, LSMO', 'services' => 'Hematology,Oncology', 'clinics' => 'Sehnaoui Building/6th floor/facing HDF', 'languages' => 'English, French, Italian, Arabic'],
            ['first_name' => 'Rami', 'last_name' => 'Bou Khalil', 'email' => 'rami.boukhalil@usj.edu.lb', 'phone' => '01604971', 'birth_date' => '4/7/1980', 'gender' => 'Male', 'main_specialization' => 'Psychiatry', 'sub_specializations' => 'Eating disorders, psychosomatic medicine', 'country' => 'Lebanon', 'first_visit_price' => '100', 'followup_price' => '70', 'education' => 'Psychiatry', 'hospitals' => 'Hotel-Dieu de France', 'memberships' => '', 'services' => 'Psychiatry', 'clinics' => 'Hotel-Dieu de France outpatient clinic', 'languages' => 'Arabic, English, French'],
            ['first_name' => 'Nabil', 'last_name' => 'Chehata', 'email' => 'nabil.chehata@hdf.usj.edu.lb', 'phone' => '', 'birth_date' => '3/20/1971', 'gender' => '', 'main_specialization' => 'Infectious Diseases', 'sub_specializations' => '', 'country' => 'Lebanon', 'first_visit_price' => '100', 'followup_price' => '70', 'education' => '', 'hospitals' => '', 'memberships' => 'SPILF, IDSA, ESCMID', 'services' => '', 'clinics' => 'Hotel-Dieu de France', 'languages' => 'FRENCH, ENGLISH, ARABIC, SPANISH'],
            ['first_name' => 'Amer', 'last_name' => 'Sebaaly', 'email' => 'amersebaaly@hotmail.com', 'phone' => '03679129', 'birth_date' => '11/20/1985', 'gender' => 'Male', 'main_specialization' => '', 'sub_specializations' => 'Spine surgery, Scoliosis', 'country' => 'Lebanon', 'first_visit_price' => '100', 'followup_price' => '70', 'education' => 'Saint Joseph University, Paris V university, Montreal University', 'hospitals' => 'Hotel-Dieu de France, Saint Joseph Hospital, Bellevue Medical Center', 'memberships' => 'France Spine Society SFCR, AO Spine Middle east', 'services' => '', 'clinics' => 'Hotel-Dieu de France 01604944, Saint Joseph Hospital 0124011 ext 1300, Bellevue Medical Center 01682666 3xt 5640', 'languages' => 'Arabic, English, French'],
            ['first_name' => 'Naim', 'last_name' => 'Bejjani', 'email' => 'naim.bejjani@gmail.com', 'phone' => '03853699', 'birth_date' => '8/15/1985', 'gender' => 'Male', 'main_specialization' => 'Pediatrician', 'sub_specializations' => 'Hematology, Oncology', 'country' => 'Lebanon', 'first_visit_price' => '100', 'followup_price' => '70', 'education' => 'Master I of Fundamental Sciences Jul 2019, Faculty of medicine, Saint Joseph University/Ashrafieh/Lebanon, Initiation to Clinical Research Certificate Jul 2019, Pediatric Immunology/Hematology Inter University Diploma Nov 2016, Universite Claude Bernard Lyon 1/France, General Pediatrics Jun 2015, Faculty of medicine, Saint Joseph University/Ashrafieh/Lebanon, Good Clinical Practice GCP Dec 2013, National Institute of Allergy/Infectious Diseases, USA, General Medicine Jun 2011, English Proficiency Apr 2005, Georgetown University/USA, Lebanese Baccalaureate Jul 2003, French Baccalaureate Jul 2003, Diploma of College Notre Dame de Jamhour/Baabda/Lebanon Jul 2003', 'hospitals' => 'Hotel-Dieu de France', 'memberships' => 'International Society of Pediatric Oncology SIOP, Lebanese Pediatric Society, Lebanese Society of Hematology/Blood Transfusion, French Society of Pediatric Hematology/Immunology', 'services' => 'Pediatric Hematology, Pediatric Oncology, General Pediatrics, Vaccination', 'clinics' => 'Hotel-Dieu de France 01604000 ext 9401, Hazmieh Clinic 76578296', 'languages' => 'French, English, Arabic'],
            ['first_name' => 'Rita', 'last_name' => 'Slim', 'email' => 'rslimkaram@hotmail.com', 'phone' => '', 'birth_date' => '3/1/1969', 'gender' => 'Female', 'main_specialization' => 'Gastroentrology, Hepatology', 'sub_specializations' => 'Therapeutic endoscopy, ERCP, Enteroscopy, VCE, Proctology', 'country' => 'Lebanon', 'first_visit_price' => '100', 'followup_price' => '70', 'education' => '', 'hospitals' => '', 'memberships' => '', 'services' => '', 'clinics' => '', 'languages' => ''],
            ['first_name' => 'Maroun', 'last_name' => 'Moukarzel', 'email' => 'marounmoukarzel@mail.com', 'phone' => '03655919', 'birth_date' => '7/1/1956', 'gender' => 'Male', 'main_specialization' => 'Urology', 'sub_specializations' => 'Urological cancers, Kidney transplantation', 'country' => 'Lebanon', 'first_visit_price' => '100', 'followup_price' => '70', 'education' => '', 'hospitals' => 'Hotel-Dieu de France', 'memberships' => '', 'services' => '', 'clinics' => '', 'languages' => 'Arabic, French, English'],
            ['first_name' => 'Toni', 'last_name' => 'Rizk', 'email' => 'tonirisk@hotmail.com', 'phone' => '03332271', 'birth_date' => '1/13/1963', 'gender' => 'Male', 'main_specialization' => 'Neurosurgery', 'sub_specializations' => 'Pediatric, spine', 'country' => 'Lebanon', 'first_visit_price' => '100', 'followup_price' => '70', 'education' => 'french board of neurosurgery', 'hospitals' => 'Hotel-Dieu de France', 'memberships' => '', 'services' => '', 'clinics' => '', 'languages' => 'Arabic,French,English'],
            ['first_name' => 'Nayla', 'last_name' => 'Matar', 'email' => 'nayla.matar@hdf.usj.edu.lb', 'phone' => '01604926', 'birth_date' => '7/25/1978', 'gender' => 'Female', 'main_specialization' => 'ENT', 'sub_specializations' => 'Laryngology', 'country' => 'Lebanon', 'first_visit_price' => '100', 'followup_price' => '70', 'education' => 'MD, PhD', 'hospitals' => 'Hotel-Dieu de France', 'memberships' => "European Laryngological Society, Societe Francaise de Laryngologie et Phoniatrie, Societe Libanaise d'ORL", 'services' => '', 'clinics' => '', 'languages' => 'Arabic, French, English'],
            ['first_name' => 'Tony', 'last_name' => 'El Murr', 'email' => 'tony.elmurr@hdf.ish.edu.lb', 'phone' => '03347473', 'birth_date' => '4/12/1973', 'gender' => 'Male', 'main_specialization' => 'Medecine Interne, Immunologie clinique', 'sub_specializations' => '', 'country' => 'Lebanon', 'first_visit_price' => '100', 'followup_price' => '70', 'education' => '', 'hospitals' => 'Hotel-Dieu de France', 'memberships' => '', 'services' => 'Internal Medicine division', 'clinics' => 'Hotel-Dieu de France, Jdeideh', 'languages' => 'Arabic, French,English'],
            ['first_name' => 'Elie', 'last_name' => 'Haddad', 'email' => 'elie.haddad@hdf.usj.edu.lb', 'phone' => '03561121', 'birth_date' => '15/02/1984', 'gender' => 'Male', 'main_specialization' => 'Infectious Disease', 'sub_specializations' => 'HIV, tuberculosis, bacterial infections', 'country' => 'France', 'first_visit_price' => '100', 'followup_price' => '70', 'education' => 'USJ, sorbonne universite, Paris Descartes', 'hospitals' => 'Hotel-Dieu de France', 'memberships' => 'Lebanese oirder of physician, French board certified, member of the ESCMID', 'services' => '', 'clinics' => 'Hotel-Dieu de Franceext 9118', 'languages' => 'French, English, Arabic'],
            ['first_name' => 'Nada', 'last_name' => 'El Ghorayeb', 'email' => 'ghorayebnada85@gmail.com', 'phone' => '03883431', 'birth_date' => '05/06/1985', 'gender' => 'Female', 'main_specialization' => 'Endocrinology', 'sub_specializations' => 'pituitary, adrenal disorders', 'country' => 'Lebanon', 'first_visit_price' => '100', 'followup_price' => '70', 'education' => 'Centre Hospitalier Universitaire de Montreal/Canada', 'hospitals' => 'Hotel-Dieu de France,Bellevue Medical Center', 'memberships' => 'lebanese society of diabetes, endocrinology, lipids', 'services' => 'Daibetes management, eduaction, weight management, osteoporosis, thyroid, parathyoid disorders, PCOS, adrenal, pituitary disorders', 'clinics' => 'Hotel-Dieu de France, Bellevue Medical Center', 'languages' => 'Arabic, French, English'],
            ['first_name' => 'Nadim', 'last_name' => 'Khoueir', 'email' => 'nadim.khoueir@hdf.usj.edu.lb', 'phone' => '03911535', 'birth_date' => '12/28/1984', 'gender' => 'Male', 'main_specialization' => 'ENT', 'sub_specializations' => 'Rhinology, Endoscopic sinus, skull base surgery', 'country' => 'Lebanon', 'first_visit_price' => '100', 'followup_price' => '70', 'education' => 'Medical diploma at Saint Joseph University/Beirut/Lebanon, ENT diploma at Saint Joseph University/Hotel-Dieu de France/Beirut/Lebanon, Rhinology Fellowship at Medstar Union Memorial Hospital/Blatimore/USA, Rhinology/Skull base Fellowship at Lariboisiere Hospital/Paris/France, Masters in Public Health/Biostatistics/Paris/Saclay University/Paris/France', 'hospitals' => 'Hotel-Dieu de France, Beirut Eye, ENT specialist Hospital', 'memberships' => 'Lebanese ENT society, American rhinologic society', 'services' => '', 'clinics' => 'Hotel-Dieu de France, Beirut Eye, ENT specialist Hospital', 'languages' => 'French, English, Arabic'],
            ['first_name' => 'Joseph', 'last_name' => 'Maarrawi', 'email' => 'joseph.maarrawi@usj.edu.lb', 'phone' => '03742374', 'birth_date' => '7/7/1971', 'gender' => 'Male', 'main_specialization' => 'Neurosurgery', 'sub_specializations' => 'Functional neurosurgery, spine', 'country' => 'Lebanon', 'first_visit_price' => '100', 'followup_price' => '70', 'education' => 'MD,PhD', 'hospitals' => 'Hotel-Dieu de France', 'memberships' => 'IASP, lebanese order of physicians, French order of physicians', 'services' => 'Surgery, pain specialist, epidural injection', 'clinics' => 'RUBIK center Beirut', 'languages' => 'Arabic, French, English'],
            ['first_name' => 'Bassem', 'last_name' => 'Habr', 'email' => 'bassem.habr@hdf.usj.edu.lb', 'phone' => '70952202', 'birth_date' => '1/1/1984', 'gender' => 'Male', 'main_specialization' => 'Pulmonary, critical care medicine', 'sub_specializations' => 'Pulmonary rehabilitation', 'country' => 'Lebanon', 'first_visit_price' => '100', 'followup_price' => '70', 'education' => 'Universite Saint Joseph, Paris Diderot, Lyon I', 'hospitals' => 'Hotel-Dieu de France', 'memberships' => '', 'services' => '', 'clinics' => '01604918', 'languages' => 'Arabic, French, English, Spanish'],
            ['first_name' => 'Lamisse', 'last_name' => 'Karam', 'email' => 'Lamisse.karam@gmail.com', 'phone' => '03639895', 'birth_date' => '1/1/1981', 'gender' => 'Female', 'main_specialization' => 'Vascular Surgery', 'sub_specializations' => 'Vascular Access Surgery, Venous microsurgery, Phlebology', 'country' => 'Lebanon', 'first_visit_price' => '100', 'followup_price' => '70', 'education' => 'Harvard Medical School, University Paris 12, University Paris 6, University Paris 5, Saint Joseph University', 'hospitals' => 'Hotel-Dieu de France', 'memberships' => 'European Society for Vascular Surgery, French Society for Vascular Access, French Society of Phlebology, Lebanese Society for Vascular Surgery', 'services' => 'Cosmetic venous surgery, Endovenous ablation techniques, Sclerotherapy, Vascular ultrasound, Vascular Laser', 'clinics' => 'Hotel-Dieu de France external clinics', 'languages' => 'Arabic, French, English'],
            ['first_name' => 'Elie', 'last_name' => 'Helou', 'email' => 'ehelou@gmail.com', 'phone' => '03477240', 'birth_date' => '7/20/1979', 'gender' => 'Male', 'main_specialization' => 'Urology', 'sub_specializations' => 'Minimally invasive surgery, urogynecology, neurourology, Infertility', 'country' => 'Lebanon', 'first_visit_price' => '100', 'followup_price' => '70', 'education' => '', 'hospitals' => 'Hotel-Dieu de France', 'memberships' => '', 'services' => '', 'clinics' => 'Hotel-Dieu de France', 'languages' => 'English, French, Arabic'],
            ['first_name' => 'Gabi', 'last_name' => 'Kreichati', 'email' => 'gaby.kreichati@usj.edu.lb', 'phone' => '03758158', 'birth_date' => '3/9/1958', 'gender' => 'Male', 'main_specialization' => 'Orthopeadic surgery', 'sub_specializations' => 'Spine, spinal deformity surgery', 'country' => 'Lebanon', 'first_visit_price' => '100', 'followup_price' => '70', 'education' => 'Medical  Doctor Diploma(1984)/Saint Joseph University/Beirut/Lebanon, Orthopeadic surgery diploma (1989)/Saint Joseph University/Beirut/Lebanon, Training in spine surgery/Four years (1988-1992), Beaujon Hospital/Pr Deburge(1989)/Paris/France, Saint Joseph Hospital/Dr Gillaumat (1990)/Paris/France, Institut Calot/Dr Chopin (1991, 1992)/Berck sur Mer/France, Professor/Faculty of Medecine/Saint Joseph University', 'hospitals' => 'Hotel-Dieu de France/Boulevard Alfred Naccache/Beirut/Lebanon', 'memberships' => 'SFCR/Societe Francaise de Chirurgie du Rachis, ESS/European Spine Society', 'services' => 'Orthopeadic surgery department/Hotel-Dieu de France/Beirut/Lebanon', 'clinics' => 'Hotel-Dieu de France', 'languages' => 'Arabic, French, English'],
            ['first_name' => 'Zeina', 'last_name' => 'Aoun Bacha', 'email' => 'zeina.aoun@hdf.usj.edu.lb', 'phone' => '03664052', 'birth_date' => '12/02/1961', 'gender' => 'Female', 'main_specialization' => 'Pulmonology', 'sub_specializations' => 'Smoking cessation', 'country' => 'Lebanon', 'first_visit_price' => '100', 'followup_price' => '70', 'education' => 'Pulmonology, Tabacology', 'hospitals' => 'Hotel-Dieu de France', 'memberships' => 'FCCP, ERS member, Previous President Lebanese Pulmonary Society, active member of EFP', 'services' => 'Asthma, COPD expert, smoking cessation expert, other pulmonary diseases in general', 'clinics' => 'Hotel-Dieu de France(Tour de Consultation afternoon), Tour Pasteur next to HDF( Morning)', 'languages' => 'Arabic, French, English'],
            ['first_name' => 'Carla', 'last_name' => 'Irani', 'email' => 'iranica@yahoo.com', 'phone' => '03495496', 'birth_date' => '12/04/1971', 'gender' => 'Female', 'main_specialization' => 'Allergy, Clinical Immunology', 'sub_specializations' => '', 'country' => 'Lebanon', 'first_visit_price' => '100', 'followup_price' => '70', 'education' => 'American Board certified in Allergy, Clinical Immunology', 'hospitals' => '', 'memberships' => '', 'services' => '', 'clinics' => '', 'languages' => ''],
            ['first_name' => 'David', 'last_name' => 'Atallah', 'email' => 'david.atallah@gmail.com', 'phone' => '03352506', 'birth_date' => '8/22/1967', 'gender' => 'Male', 'main_specialization' => 'Obstetrics, Gynecology', 'sub_specializations' => 'Gynecologic, Oncologic', 'country' => 'Lebanon', 'first_visit_price' => '100', 'followup_price' => '70', 'education' => 'Saint Joseph University (MD), Liverpool university UK (Masters in Science), Institut Gustave Roussy Villejuif France (Fellowship)', 'hospitals' => 'Hotel-Dieu de France, Chairman of Department', 'memberships' => 'international Gynecologic Cancer Society, Middle east mediterranean association of Gynecologist oncologists, President elect of the lebansese society of Obstetrics, gynecology, Society of gynecologists oncologists (USA), European Society of Gynecologic Oncology', 'services' => 'specialized in breast, gynecologic cancers, minimally invasive surgery, Placenta accreta Spectrum center of excellence', 'clinics' => 'Hotel-Dieu de France extension 9415, Tayouneh/Furn el chebback 03352506 or 01381530', 'languages' => 'French, English, Arabic'],
            ['first_name' => 'Farid', 'last_name' => 'Stephan', 'email' => 'farid.stephan@hdf.usj.edu.lb', 'phone' => '01616165', 'birth_date' => '1/1/1974', 'gender' => 'Male', 'main_specialization' => 'Dermatology', 'sub_specializations' => 'surgical dermatology, dermoscopy, lasers', 'country' => 'Lebanon, France', 'first_visit_price' => '100', 'followup_price' => '70', 'education' => 'USJ, Paris 12, Universite Paris Cite, Universite de Versailles', 'hospitals' => 'Hotel-Dieu de France, Henri Mondor, Tenon hospital', 'memberships' => 'Lebanese society of dermatology,French society of dermatology', 'services' => 'dermatology', 'clinics' => 'Hotel-Dieu de France, Private clinic', 'languages' => 'Arabic, French, English'],
            ['first_name' => 'Sami', 'last_name' => 'Slaba', 'email' => 'sslaba@hotmail.com', 'phone' => '03704870', 'birth_date' => '10/17/1964', 'gender' => 'Male', 'main_specialization' => 'Radiology', 'sub_specializations' => 'Interventional Radiology', 'country' => 'Lebanon', 'first_visit_price' => '100', 'followup_price' => '70', 'education' => 'Professor', 'hospitals' => 'Hotel-Dieu de France', 'memberships' => 'SFR, PAIRS', 'services' => '', 'clinics' => '', 'languages' => 'Arabic, French, English'],
            ['first_name' => 'Gebrael', 'last_name' => 'Saliba', 'email' => 'gebraelsaliba@gmail.com', 'phone' => '76967222', 'birth_date' => '1/8/1976', 'gender' => 'Male', 'main_specialization' => 'Infectious Diseases', 'sub_specializations' => 'HIV, STDs, Vaccines, Tropical Medicine, Travel Medicine', 'country' => 'Lebanon', 'first_visit_price' => '100', 'followup_price' => '70', 'education' => 'Universite Saint Joseph, Universite Paris VI/France', 'hospitals' => 'Hotel-Dieu de France', 'memberships' => '', 'services' => '', 'clinics' => 'Hotel-Dieu de France', 'languages' => 'Arabic, French, English'],
            ['first_name' => 'Jeanine', 'last_name' => 'El Helou', 'email' => 'jeaninelhelou@gmail.com', 'phone' => '03262586', 'birth_date' => '5/12/1977', 'gender' => 'Female', 'main_specialization' => 'Neurology', 'sub_specializations' => 'Epilepsy, Sleep disorders', 'country' => 'Lebanon', 'first_visit_price' => '100', 'followup_price' => '70', 'education' => 'Saint Joseph University of Beirut, Sorbonne University Paris', 'hospitals' => 'Hotel-Dieu de France', 'memberships' => '', 'services' => 'General Neurology, Epilepsy, Sleep disorders', 'clinics' => 'Hotel-Dieu de France', 'languages' => 'Arabic, French, English, Spanish'],
            ['first_name' => 'Simon', 'last_name' => 'Rassi', 'email' => 'simon.rassi@hdf.usj.edu.lb', 'phone' => '03884203, 76302378, 01604931', 'birth_date' => '19/11/1970', 'gender' => 'Male', 'main_specialization' => 'ORL', 'sub_specializations' => 'Pediatric ORL', 'country' => 'Lebanon', 'first_visit_price' => '100', 'followup_price' => '70', 'education' => 'USJ,FM Paris', 'hospitals' => 'Hotel-Dieu de France', 'memberships' => 'IFOS', 'services' => 'ORL', 'clinics' => 'Hotel-Dieu de France', 'languages' => 'Arabic, French, English'],
            ['first_name' => 'Tony', 'last_name' => 'Abdel Massih', 'email' => 'tony.abdelmassih@usj.edu.lb', 'phone' => '03354357', 'birth_date' => '11/22/1970', 'gender' => 'Male', 'main_specialization' => 'Cardiology', 'sub_specializations' => 'heart failure, cardiac ultrasound', 'country' => 'Lebanon', 'first_visit_price' => '100', 'followup_price' => '70', 'education' => 'Medical Degree USJ(beirut), cardoiology diploma USJ(beirut), ECHO, HEART FAILURE DEGRE Rene Descartes (PARIS)', 'hospitals' => 'Hotel-Dieu de France', 'memberships' => 'european society of cardiology,lebanese society of cardiology', 'services' => 'cardiology, heart failure unit', 'clinics' => 'Consultation building/first floor', 'languages' => 'Arabic, French, English'],
            ['first_name' => 'Nelly', 'last_name' => 'Ziade', 'email' => 'nellziade@yahoo.fr', 'phone' => '01312013', 'birth_date' => '1/1/1976', 'gender' => 'Female', 'main_specialization' => 'Rheumatology', 'sub_specializations' => 'Epidemiology', 'country' => 'Lebanon', 'first_visit_price' => '100', 'followup_price' => '70', 'education' => 'USJ, Paris XI, Paris V', 'hospitals' => 'Hotel-Dieu de France', 'memberships' => 'Lebanese Society of Rheumatology, French Society of Rheumatology, European Alliance of Rheumatology Associations, Arab League of Associations for Rheumatology, Assessment of SpondyloArthritis International Society, Royal College of Physicians of London', 'services' => 'Rheumatology consultation', 'clinics' => 'Achrafieh', 'languages' => 'Arabic, French, English'],
            ['first_name' => 'Zeina', 'last_name' => 'Kadri', 'email' => 'zkadri@hotmail.com', 'phone' => '70967446', 'birth_date' => '2/21/1976', 'gender' => 'Female', 'main_specialization' => 'Cardiologist', 'sub_specializations' => 'intensive care, echo', 'country' => 'Lebanon', 'first_visit_price' => '100', 'followup_price' => '70', 'education' => 'usj, paris', 'hospitals' => 'Hotel-Dieu de France', 'memberships' => 'ESC', 'services' => 'cardio,ICU', 'clinics' => 'Hotel-Dieu de France', 'languages' => 'French, Arabic, English, German'],
            ['first_name' => 'Lynn', 'last_name' => 'Abdo', 'email' => 'line_abdo@hotmail.com', 'phone' => '03318132', 'birth_date' => '1/1/1986', 'gender' => 'Female', 'main_specialization' => 'Internal medicine', 'sub_specializations' => 'palliative care, geriatrics', 'country' => 'Lebanon', 'first_visit_price' => '100', 'followup_price' => '70', 'education' => 'Saint joseph university,Paris VI university', 'hospitals' => 'Hotel-Dieu de France', 'memberships' => 'internal medicine society', 'services' => '', 'clinics' => 'Hotel-Dieu de France', 'languages' => 'English , French, Arabic, Spanish'],
            ['first_name' => 'Charline', 'last_name' => 'El Hachem', 'email' => 'charlineeh@gmail.com', 'phone' => '03725576', 'birth_date' => '21/08/1983', 'gender' => 'Female', 'main_specialization' => 'Psychiatry', 'sub_specializations' => 'Addictology, Perinatal psychiatry', 'country' => 'Lebanon', 'first_visit_price' => '100', 'followup_price' => '70', 'education' => '', 'hospitals' => 'Hotel-Dieu de France', 'memberships' => 'Vice president of the LPS', 'services' => '', 'clinics' => 'Hotel-Dieu de France', 'languages' => 'Arabic, French, English'],
            ['first_name' => 'Nina', 'last_name' => 'Mouawad', 'email' => 'ninamouawadclinic@hotmail.com', 'phone' => '03650180', 'birth_date' => '02/09/1969', 'gender' => 'Female', 'main_specialization' => 'Obstetrics, Gynecology', 'sub_specializations' => 'Infertility', 'country' => 'Lebanon', 'first_visit_price' => '100', 'followup_price' => '70', 'education' => 'USJ', 'hospitals' => 'Hotel-Dieu de France, HSC, Levant', 'memberships' => 'LSOG, LSQSH', 'services' => '', 'clinics' => 'Hazmieh private clinic', 'languages' => 'French, English, Arabic'],
            ['first_name' => 'Ghada', 'last_name' => 'Abi Karam', 'email' => 'gabikaram7@gmail.com', 'phone' => '03846812', 'birth_date' => '21/4/1969', 'gender' => 'Female', 'main_specialization' => 'Rheumatology', 'sub_specializations' => '', 'country' => 'Lebanon', 'first_visit_price' => '100', 'followup_price' => '70', 'education' => '', 'hospitals' => 'Hotel-Dieu de France', 'memberships' => '', 'services' => '', 'clinics' => '', 'languages' => ''],
            ['first_name' => 'Ramzi', 'last_name' => 'Finan', 'email' => 'ramzifinan@hotmail.com', 'phone' => '03608225', 'birth_date' => '2/6/1956', 'gender' => 'Male', 'main_specialization' => 'ob gyn', 'sub_specializations' => 'microchirurgie tubaire', 'country' => 'Lebanon', 'first_visit_price' => '100', 'followup_price' => '70', 'education' => 'USJ, toulouse France', 'hospitals' => 'Hotel-Dieu de France', 'memberships' => 'LSOG (president), FeFOG (vice president), CNGOF FACS', 'services' => '', 'clinics' => 'Hotel-Dieu de France, newjdeydeh', 'languages' => 'French, English, Arabic'],
            ['first_name' => 'Sami', 'last_name' => 'Roukoz', 'email' => 'samiroukoz@gmail.com', 'phone' => '03704875', 'birth_date' => '', 'gender' => 'Male', 'main_specialization' => 'Orthopedic surgery', 'sub_specializations' => 'Shoulder and Hand surgery', 'country' => 'Lebanon', 'first_visit_price' => '100', 'followup_price' => '70', 'education' => 'Medical Doctor Professor', 'hospitals' => 'Hotel-Dieu de France', 'memberships' => 'AOT Faculty', 'services' => '', 'clinics' => '', 'languages' => 'French, English, Arabic'],
            ['first_name' => 'Rami', 'last_name' => 'Rachkidi', 'email' => 'info@ramirachkidi.com', 'phone' => '03776070', 'birth_date' => '9/1/1978', 'gender' => 'Male', 'main_specialization' => 'Orthopedics', 'sub_specializations' => 'Spine surgery', 'country' => 'Lebanon', 'first_visit_price' => '100', 'followup_price' => '70', 'education' => 'USJ, Hotel-Dieu de France, France', 'hospitals' => 'Hotel-Dieu de France, MLH', 'memberships' => '', 'services' => '', 'clinics' => '', 'languages' => 'French, English, Arabic'],
            ['first_name' => 'Raymond', 'last_name' => 'Michael', 'email' => 'alexantoine@idm.net.lb', 'phone' => '03704878', 'birth_date' => '', 'gender' => 'Female', 'main_specialization' => 'pediatrie', 'sub_specializations' => 'maladies infectieuse, immunologie, allergologie, rhumatologie', 'country' => '', 'first_visit_price' => '100', 'followup_price' => '70', 'education' => '', 'hospitals' => '', 'memberships' => '', 'services' => '', 'clinics' => '', 'languages' => ''],
            ['first_name' => 'Georges', 'last_name' => 'Dabar', 'email' => 'georges.dabar@usj.edu.lb', 'phone' => '03255060', 'birth_date' => '11/25/1966', 'gender' => 'Male', 'main_specialization' => 'Pulmonology', 'sub_specializations' => 'pulmonology, critical care', 'country' => 'Lebanon', 'first_visit_price' => '100', 'followup_price' => '70', 'education' => 'St Joseph Medical School, Residency and Fellowship at Harvard Medical School, Tufts University', 'hospitals' => 'Hotel-Dieu de France', 'memberships' => 'American College of Chest Physicians', 'services' => 'Pneumologie  et Reanimation', 'clinics' => 'Hotel-Dieu de France', 'languages' => 'French, English, Arabic'],
            ['first_name' => 'Nadine', 'last_name' => 'El Kassis', 'email' => 'Nadine.kassis@gmail.com', 'phone' => '03216486', 'birth_date' => '7/15/1981', 'gender' => 'Female', 'main_specialization' => 'Chirurgie gynecologique et obstetrique', 'sub_specializations' => 'chirurgie du sein, chirurgie onco gynecologique, urogynécologique', 'country' => 'Lebanon', 'first_visit_price' => '100', 'followup_price' => '70', 'education' => 'medecine generale et gynecologie obstetrique universite saint joseph, Diplome universitaire de coelioscopie, Diplome d echographie gynecologique et obstetrique: paris descartes, Attestation de formation specialisee en gynecologie obstetrique de paris descartes, Diplome de chirurgie et prise en charge du cancer du sein paris 6, master 2 en recherches cliniques et biologiques: USJ', 'hospitals' => '', 'memberships' => '', 'services' => '', 'clinics' => '', 'languages' => ''],
            ['first_name' => 'Ghassan', 'last_name' => 'Chakhtoura', 'email' => 'ghassan.chakhtoura@hdf.usj.edu.lb', 'phone' => '01604938, 03336121', 'birth_date' => '2/22/1973', 'gender' => 'Male', 'main_specialization' => 'Speciality Digestive, Endocrine surgery', 'sub_specializations' => 'Colo-rectal, bariatric surgery Country', 'country' => 'Lebanon', 'first_visit_price' => '100', 'followup_price' => '70', 'education' => '', 'hospitals' => '', 'memberships' => '', 'services' => '', 'clinics' => 'Hotel-Dieu de France third floor, Clinics tower', 'languages' => 'French, English, Arabic'],
            ['first_name' => 'Halim', 'last_name' => 'Abboud', 'email' => 'halimabboud@gmail.com', 'phone' => '01604936', 'birth_date' => '12/6/1971', 'gender' => 'Male', 'main_specialization' => 'Neurologist', 'sub_specializations' => 'Stroke, headache, pain, MS', 'country' => 'Lebanon', 'first_visit_price' => '100', 'followup_price' => '70', 'education' => '', 'hospitals' => 'Hotel-Dieu de France', 'memberships' => '', 'services' => 'Head of departmentNeurology', 'clinics' => 'Hotel-Dieu de France', 'languages' => 'Arabic, French, English'],
            ['first_name' => 'Toni', 'last_name' => 'Mansour', 'email' => 'drtonimansour@gmail.com', 'phone' => '01604967', 'birth_date' => '12/7/1987', 'gender' => 'Male', 'main_specialization' => 'Orthopedic Surgery', 'sub_specializations' => 'Hip and Knee and foot surgery', 'country' => 'Lebanon', 'first_visit_price' => '100', 'followup_price' => '70', 'education' => 'Saint Joseph University/Beyrouth/Liban, Universite Paris V Descartes/Paris/France, Schulthess Klinik/Zurich/Suisse', 'hospitals' => 'Hotel-Dieu de France/Beyrouth, Mount Lebanon Hospital/Hazmyeh', 'memberships' => 'Lebanese order of physicians, Lebanese orthopedic society, American Academy of orthopedic surgery', 'services' => '', 'clinics' => 'Hotel-Dieu de France external clinics/6th floor, Mount Lebanon hospital external clinics/6th floor', 'languages' => 'Arabic, French, English'],
            ['first_name' => 'Marie-Helene', 'last_name' => 'Gannage-Yared', 'email' => 'mariehelene.yared@usj.edu.lb', 'phone' => '03291301', 'birth_date' => '11/24/1961', 'gender' => 'Female', 'main_specialization' => 'Endocrinology, Metabolism (Diabetes)', 'sub_specializations' => '', 'country' => 'Lebanon', 'first_visit_price' => '100', 'followup_price' => '70', 'education' => 'MD,MSc', 'hospitals' => 'Hotel-Dieu de France', 'memberships' => 'Endocrine Society', 'services' => 'Consultations', 'clinics' => '', 'languages' => 'French, English, Arabic'],
        ];

        foreach ($rows as $row) {
            if (! trim(Arr::get($row, 'email', ''))) {
                continue;
            }

            $langList = array_values(array_filter(array_map(fn ($l) => trim($l), explode(',', Arr::get($row, 'languages', '')))));
            $specialtyNames = array_values(array_filter(array_map(fn ($s) => trim($s), explode(',', Arr::get($row, 'main_specialization', '')))));
            $primarySpecialty = null;
            if ($specialtyNames) {
                $primarySpecialty = Specialty::firstOrCreate(['name' => $specialtyNames[0]]);
            }

            $user = User::firstOrCreate(
                ['email' => trim($row['email'])],
                [
                    'name' => trim(($row['first_name'] ?? '') . ' ' . ($row['last_name'] ?? '')),
                    'role' => 'doctor',
                    'password' => bcrypt('password'),
                ]
            );
            if (! $user->hasRole($doctorRole->name)) {
                $user->assignRole($doctorRole);
            }
            if ($doctorRole->permissions()->exists()) {
                $user->syncPermissions($doctorRole->permissions);
            }

            $doctor = Doctor::updateOrCreate(
                ['user_id' => $user->id],
                [
                    'first_name' => trim($row['first_name'] ?? ''),
                    'last_name' => trim($row['last_name'] ?? ''),
                    'display_name' => trim(($row['first_name'] ?? '') . ' ' . ($row['last_name'] ?? '')),
                    'designation' => $primarySpecialty?->name,
                    'phone' => trim($row['phone'] ?? ''),
                    'email' => trim($row['email'] ?? ''),
                    'languages_json' => $langList ? json_encode($langList) : null,
                    'profile_image_path' => null,
                    'bio' => null,
                    'rating_avg' => 5.0,
                    'default_fee' => is_numeric($row['first_visit_price']) ? (float) $row['first_visit_price'] : null,
                    'city' => '',
                    'country' => trim($row['country'] ?? ''),
                ]
            );

            Clinic::updateOrCreate(
                [
                    'doctor_id' => $doctor->id,
                    'name' => 'Hotel-Dieu de France',
                ],
                [
                    'address' => null,
                    'city' => $doctor->city ?? '',
                    'image_url' => null,
                ]
            );

            $serviceNames = array_values(array_filter(array_map(fn ($s) => trim($s), explode(',', Arr::get($row, 'services', '')))));
            if (! $serviceNames) {
                $serviceNames = $specialtyNames ?: array_values(array_filter(array_map(fn ($s) => trim($s), explode(',', Arr::get($row, 'sub_specializations', '')))));
            }

            foreach ($serviceNames as $serviceName) {
                $serviceSpecialty = Specialty::firstOrCreate(['name' => $serviceName]);
                DoctorService::updateOrCreate(
                    [
                        'doctor_id' => $doctor->id,
                        'name' => $serviceName,
                    ],
                    [
                        'specialty_id' => $serviceSpecialty->id,
                        'price' => is_numeric($row['first_visit_price']) ? (float) $row['first_visit_price'] : null,
                        'description' => null,
                    ]
                );
            }

            $clinicChunks = array_values(array_filter(array_map(fn ($c) => trim($c), explode(',', Arr::get($row, 'clinics', '')))));
            if ($clinicChunks) {
                $first = array_shift($clinicChunks);
                Clinic::updateOrCreate(
                    [
                        'doctor_id' => $doctor->id,
                        'name' => $first ?: ($doctor->display_name . ' Clinic'),
                    ],
                    [
                        'address' => $clinicChunks ? implode(', ', $clinicChunks) : null,
                        'city' => '',
                    ]
                );
            }

            $membershipEntries = array_values(array_filter(array_map(fn ($m) => trim($m), explode(',', Arr::get($row, 'memberships', '')))));
            foreach ($membershipEntries as $memberTitle) {
                Membership::updateOrCreate(
                    ['doctor_id' => $doctor->id, 'title' => $memberTitle],
                    ['description' => null]
                );
            }
        }
    }
}
